apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: zero-trust-simple-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-app
  severity: 10
  message: "Zero-trust: only allow wisecow app expected behavior"
  process:
    matchPaths:
      - path: /bin/sh
      - path: /bin/ls
      - path: /bin/cat
      - path: /usr/bin/python3
  file:
    matchDirectories:
      - dir: /app
        recursive: true
      - dir: /etc/ssl
        recursive: true
      - dir: /usr/lib
        recursive: true
      - dir: /lib
        recursive: true
    matchPaths:
      - path: /dev/null
  network:
    matchProtocols:
      - protocol: tcp
    matchPorts:
      - port: 4499
  capabilities:
    matchCapabilities:
      - capability: net_raw
  action: Block
