apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: zero-trust-simple-app-permissive
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-app
  severity: 1   # minimum allowed value
  message: "Permissive: no blocking for testing"
  process:
    matchPaths: []
  file:
    matchDirectories: []
    matchPaths: []
  network:
    matchProtocols: []
  capabilities:
    matchCapabilities: []
  action: Allow
