apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-etc-write
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-app  
  process:
    matchPaths:
      - path: /etc
        action: Block
  file:
    matchPaths:
      - path: /etc
        action: Block
